namespace:
  name: dev

replicaCount: 1

service:
  nodePort: 30081

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

pdb:
  minAvailable: 1

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  cpuAverageUtilization: 50
  memoryAverageUtilization: 70
