apiVersion: v1
kind: Namespace
metadata:
  name: kaiko-app
  labels:
    team: platform
    environment: dev
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace
  namespace: kaiko-app
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              team: platform
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: kaiko-app
stringData:
  GREETING: "Hello World!"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: kaiko-app
data:
  READINESS_DELAY_SEC: "15"
  FAIL_RATE: "0.3"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kaiko-app-quota
  namespace: kaiko-app
spec:
  hard:
    pods: "10"
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"
    # persistentvolumeclaims: "2"