apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../common/namespace.yaml
  - ../common/networkpolicy.yaml

namespace: prd

configMapGenerator:
  - name: env-config
    literals:
      - ENV=prd
