apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seed
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/asaid997/argocd-app.git
    path: argocd-app
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
